Algoritmo "a- quadrado de 15 à 200"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor    : Obama 
// Descrição   : Fazer um laço de repetição mostrando o quadrado dos números de 15 à 200
// Autor(a)    : Michelly
// Data atual  : 04/04/2022
Var
// Seção de Declarações das variáveis 
contadora:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
para contadora de 15 ate 200 passo 1 faca
escreval(contadora, "² = ", contadora^2)
fimpara

Fimalgoritmo