Algoritmo "L04B"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor    : Obama 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Michelly
// Data atual  : 20/04/2022
Var
// Seção de Declarações das variáveis 
contadora, valor:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
para contadora de 2 ate 500 passo 2 faca
valor<- valor+contadora
fimpara
escreval("A soma final é de ", valor)

Fimalgoritmo