Algoritmo "C- Soma dos valores pares"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor    : Obama
// Descrição   : Resultados da soma dos valores pares de 1 á 500
// Autor(a)    : Michelly
// Data atual  : 04/04/2022
Var
   // Seção de Declarações das variáveis
   contador,soma:inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   para contador de 2 até 500 passo 2 faca
      soma<- contador+soma
   fimpara
   escreval(soma)


Fimalgoritmo