Algoritmo "L05C"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor    : Obama
// Descrição   : Apresentar o resultado da tabuáda de 1 à 10
// Autor(a)    : Michelly
// Data atual  : 21/04/2022
Var
// Seção de Declarações das variáveis 
contadora, soma:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
contadora<-0
soma<- 0
para contadora de 1 ate 100 faca
soma<- contadora+soma
fimpara
escreval("A soma de 1 até 100 é de:",soma)
Fimalgoritmo