Algoritmo "L05G"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor    : Obama
// Descrição   : Apresentar o resultado da tabuáda de 1 à 10
// Autor(a)    : Michelly
// Data atual  : 21/04/2022
Var
// Seção de Declarações das variáveis 
contadora:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
enquanto contadora < 16 faca
escreval(contadora,"³ =",(contadora*contadora*contadora))
contadora<- contadora+1
fimenquanto
Fimalgoritmo