Algoritmo "c- soma dos números inteiros"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor    : Obama
// Descrição   : Apresentar o resultado da tabuáda de 1 à 10
// Autor(a)    : Michelly
// Data atual  : 04/04/2022
Var
   // Seção de Declarações das variáveis
   numero1,numero2:inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
 numero<-1
  para numero1 de 1 ate 500 faca passo 1
  escreval(numero1," +",numero1+numero2)

Fimalgoritmo