Algoritmo "f- troca de valores"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor    : Obama 
// Descrição   : Lêr valor de A e B e inverter os valores.
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 30/03/2022
Var
// Seção de Declarações das variáveis 
A,B,aux:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval("Escreva o valor de A: ")
leia(A)
Escreval("Escreva o valor de B: ")
leia(B)

escreval("A=",B," B=",A)

Fimalgoritmo